[package]
name = "ocsf-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"

[[bin]]
name = "ocsf-parser"
path = "src/main.rs"

[[bin]]
name = "sample-parser"
path = "src/sample.rs"
